//array of words that will be used in hangman game
var wordBank = ['BLUE', 'DINOSAUR', 'HILLBILLY', 'SNAP BACK', 'IPAD PRO', 'MISSISSIPPI RIVER', 'WITH GREAT POWER COMES GREAT RESPONSIBILITY',
	'A SERIES OF UNFORTUNATE EVENTS', 'TRANSFORMERS', 'DOLPHIN', 'STEP BROTHERS', 'GLADE', 'TEDDY BEAR', 'TEENAGE MUTANT NINJA TURTLES',
	'WHALE', 'ADVENTURE', 'BLUEBERRY', 'PARK RANGER', 'RAIN COAT', 'DANCING IN THE RAIN', 'FRIENDS', 'CINEMATIC ADVENTURES', 'DUDE WHERES MY CAR',
	'ALONG CAME POLLY', 'RETURN OF THE JEDI'];

module.exports = wordBank;
